/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorsiRouteImport } from './routes/corsi'
import { Route as ApplicazioniRouteImport } from './routes/applicazioni'
import { Route as IndexRouteImport } from './routes/index'

const CorsiRoute = CorsiRouteImport.update({
  id: '/corsi',
  path: '/corsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicazioniRoute = ApplicazioniRouteImport.update({
  id: '/applicazioni',
  path: '/applicazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applicazioni' | '/corsi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applicazioni' | '/corsi'
  id: '__root__' | '/' | '/applicazioni' | '/corsi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicazioniRoute: typeof ApplicazioniRoute
  CorsiRoute: typeof CorsiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicazioni': {
      id: '/applicazioni'
      path: '/applicazioni'
      fullPath: '/applicazioni'
      preLoaderRoute: typeof ApplicazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicazioniRoute: ApplicazioniRoute,
  CorsiRoute: CorsiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
