/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorsiRouteImport } from './routes/corsi'
import { Route as ControlliGratuitiRouteImport } from './routes/controlli-gratuiti'
import { Route as AssistenzaGdprRouteImport } from './routes/assistenza-gdpr'
import { Route as ApplicazioniRouteImport } from './routes/applicazioni'
import { Route as IndexRouteImport } from './routes/index'

const CorsiRoute = CorsiRouteImport.update({
  id: '/corsi',
  path: '/corsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlliGratuitiRoute = ControlliGratuitiRouteImport.update({
  id: '/controlli-gratuiti',
  path: '/controlli-gratuiti',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenzaGdprRoute = AssistenzaGdprRouteImport.update({
  id: '/assistenza-gdpr',
  path: '/assistenza-gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicazioniRoute = ApplicazioniRouteImport.update({
  id: '/applicazioni',
  path: '/applicazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
  id:
    | '__root__'
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicazioniRoute: typeof ApplicazioniRoute
  AssistenzaGdprRoute: typeof AssistenzaGdprRoute
  ControlliGratuitiRoute: typeof ControlliGratuitiRoute
  CorsiRoute: typeof CorsiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlli-gratuiti': {
      id: '/controlli-gratuiti'
      path: '/controlli-gratuiti'
      fullPath: '/controlli-gratuiti'
      preLoaderRoute: typeof ControlliGratuitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistenza-gdpr': {
      id: '/assistenza-gdpr'
      path: '/assistenza-gdpr'
      fullPath: '/assistenza-gdpr'
      preLoaderRoute: typeof AssistenzaGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicazioni': {
      id: '/applicazioni'
      path: '/applicazioni'
      fullPath: '/applicazioni'
      preLoaderRoute: typeof ApplicazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicazioniRoute: ApplicazioniRoute,
  AssistenzaGdprRoute: AssistenzaGdprRoute,
  ControlliGratuitiRoute: ControlliGratuitiRoute,
  CorsiRoute: CorsiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
