/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelecamereRouteImport } from './routes/telecamere'
import { Route as MinifatRouteImport } from './routes/minifat'
import { Route as GpsRouteImport } from './routes/gps'
import { Route as CorsiRouteImport } from './routes/corsi'
import { Route as ControlliGratuitiRouteImport } from './routes/controlli-gratuiti'
import { Route as AssistenzaGdprRouteImport } from './routes/assistenza-gdpr'
import { Route as ApplicazioniRouteImport } from './routes/applicazioni'
import { Route as IndexRouteImport } from './routes/index'

const TelecamereRoute = TelecamereRouteImport.update({
  id: '/telecamere',
  path: '/telecamere',
  getParentRoute: () => rootRouteImport,
} as any)
const MinifatRoute = MinifatRouteImport.update({
  id: '/minifat',
  path: '/minifat',
  getParentRoute: () => rootRouteImport,
} as any)
const GpsRoute = GpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsiRoute = CorsiRouteImport.update({
  id: '/corsi',
  path: '/corsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlliGratuitiRoute = ControlliGratuitiRouteImport.update({
  id: '/controlli-gratuiti',
  path: '/controlli-gratuiti',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenzaGdprRoute = AssistenzaGdprRouteImport.update({
  id: '/assistenza-gdpr',
  path: '/assistenza-gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicazioniRoute = ApplicazioniRouteImport.update({
  id: '/applicazioni',
  path: '/applicazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
  '/gps': typeof GpsRoute
  '/minifat': typeof MinifatRoute
  '/telecamere': typeof TelecamereRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
  '/gps': typeof GpsRoute
  '/minifat': typeof MinifatRoute
  '/telecamere': typeof TelecamereRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicazioni': typeof ApplicazioniRoute
  '/assistenza-gdpr': typeof AssistenzaGdprRoute
  '/controlli-gratuiti': typeof ControlliGratuitiRoute
  '/corsi': typeof CorsiRoute
  '/gps': typeof GpsRoute
  '/minifat': typeof MinifatRoute
  '/telecamere': typeof TelecamereRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
    | '/gps'
    | '/minifat'
    | '/telecamere'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
    | '/gps'
    | '/minifat'
    | '/telecamere'
  id:
    | '__root__'
    | '/'
    | '/applicazioni'
    | '/assistenza-gdpr'
    | '/controlli-gratuiti'
    | '/corsi'
    | '/gps'
    | '/minifat'
    | '/telecamere'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicazioniRoute: typeof ApplicazioniRoute
  AssistenzaGdprRoute: typeof AssistenzaGdprRoute
  ControlliGratuitiRoute: typeof ControlliGratuitiRoute
  CorsiRoute: typeof CorsiRoute
  GpsRoute: typeof GpsRoute
  MinifatRoute: typeof MinifatRoute
  TelecamereRoute: typeof TelecamereRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telecamere': {
      id: '/telecamere'
      path: '/telecamere'
      fullPath: '/telecamere'
      preLoaderRoute: typeof TelecamereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minifat': {
      id: '/minifat'
      path: '/minifat'
      fullPath: '/minifat'
      preLoaderRoute: typeof MinifatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gps': {
      id: '/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlli-gratuiti': {
      id: '/controlli-gratuiti'
      path: '/controlli-gratuiti'
      fullPath: '/controlli-gratuiti'
      preLoaderRoute: typeof ControlliGratuitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistenza-gdpr': {
      id: '/assistenza-gdpr'
      path: '/assistenza-gdpr'
      fullPath: '/assistenza-gdpr'
      preLoaderRoute: typeof AssistenzaGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicazioni': {
      id: '/applicazioni'
      path: '/applicazioni'
      fullPath: '/applicazioni'
      preLoaderRoute: typeof ApplicazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicazioniRoute: ApplicazioniRoute,
  AssistenzaGdprRoute: AssistenzaGdprRoute,
  ControlliGratuitiRoute: ControlliGratuitiRoute,
  CorsiRoute: CorsiRoute,
  GpsRoute: GpsRoute,
  MinifatRoute: MinifatRoute,
  TelecamereRoute: TelecamereRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
